INSERT INTO COURSE(ID, NAME) VALUES (1,'INFORMATION TECHNOLOGY');
INSERT INTO COURSE(ID, NAME) VALUES (2,'ANGULAR');
INSERT INTO COURSE(ID, NAME) VALUES (3,'HIBERNATE');

INSERT INTO REVIEW (ID, RATE, DESCRIPTION,COURSE_ID) VALUES (1001,1, 'OK', 1);
INSERT INTO REVIEW (ID, RATE, DESCRIPTION,COURSE_ID) VALUES (1002,2, 'GOOD', 1);
INSERT INTO REVIEW (ID, RATE, DESCRIPTION,COURSE_ID) VALUES (1003,3, 'VERY GOOD',1);
INSERT INTO REVIEW (ID, RATE, DESCRIPTION,COURSE_ID) VALUES (1004,4, 'EXCELLENT',2);
INSERT INTO REVIEW (ID, RATE, DESCRIPTION,COURSE_ID) VALUES (1005,5, 'OUTSTANDING',2);

INSERT INTO PASSPORT (ID, PASSPORT_ID, UPDATED_TIMESTAMP,CREATION_TIMESTAMP) VALUES (1,'PQR22845', SYSDATE,SYSDATE);
INSERT INTO PASSPORT (ID, PASSPORT_ID, UPDATED_TIMESTAMP,CREATION_TIMESTAMP) VALUES (2,'KOUP1254', SYSDATE,SYSDATE);
INSERT INTO PASSPORT (ID, PASSPORT_ID, UPDATED_TIMESTAMP,CREATION_TIMESTAMP) VALUES (3,'PAPPK665', SYSDATE,SYSDATE);

INSERT INTO STUDENT (ID, NAME,UPDATED_TIMESTAMP, CREATION_TIMESTAMP) VALUES(1,'SUDIP',SYSDATE,SYSDATE);
INSERT INTO STUDENT (ID, NAME,UPDATED_TIMESTAMP, CREATION_TIMESTAMP) VALUES(2,'POOJA',SYSDATE,SYSDATE);
INSERT INTO STUDENT (ID, NAME,UPDATED_TIMESTAMP, CREATION_TIMESTAMP) VALUES(3,'RAKESH',SYSDATE,SYSDATE);

UPDATE STUDENT S SET S.PASSPORT_ID = 1 WHERE S.ID =1;
UPDATE STUDENT S SET S.PASSPORT_ID = 2 WHERE S.ID =2;
UPDATE STUDENT S SET S.PASSPORT_ID = 3 WHERE S.ID =3;

INSERT INTO CURRENCY  VALUES (1, 'INDIAN RUPEE',SYSDATE,SYSDATE);
INSERT INTO CURRENCY  VALUES (2, 'PAKISTANI RUPEE', SYSDATE,SYSDATE);