INSERT INTO COURSE(ID, NAME) VALUES (1,'INFORMATION TECHNOLOGY');
INSERT INTO COURSE(ID, NAME) VALUES (2,'ANGULAR');
INSERT INTO COURSE(ID, NAME) VALUES (3,'HIBERNATE');

INSERT INTO PASSPORT (ID, PASSPORT_ID, UPDATED_TIMESTAMP,CREATION_TIMESTAMP) VALUES (1,'PQR22845', SYSDATE,SYSDATE);
INSERT INTO PASSPORT (ID, PASSPORT_ID, UPDATED_TIMESTAMP,CREATION_TIMESTAMP) VALUES (2,'KOUP1254', SYSDATE,SYSDATE);
INSERT INTO PASSPORT (ID, PASSPORT_ID, UPDATED_TIMESTAMP,CREATION_TIMESTAMP) VALUES (3,'PAPPK665', SYSDATE,SYSDATE);

insert into student (id, name,UPDATED_TIMESTAMP, CREATION_TIMESTAMP) values(1,'Sudip',sysdate,sysdate);
insert into student (id, name,UPDATED_TIMESTAMP, CREATION_TIMESTAMP) values(2,'Pooja',sysdate,sysdate);
insert into student (id, name,UPDATED_TIMESTAMP, CREATION_TIMESTAMP) values(3,'Rakesh',sysdate,sysdate);

UPDATE STUDENT S SET S.PASSPORT_ID = 1 WHERE S.ID =1;
UPDATE STUDENT S SET S.PASSPORT_ID = 2 WHERE S.ID =2;
UPDATE STUDENT S SET S.PASSPORT_ID = 3 WHERE S.ID =3;

INSERT INTO CURRENCY  VALUES (1, 'INDIAN RUPEE',SYSDATE,SYSDATE);
INSERT INTO CURRENCY  VALUES (2, 'PAKISTANI RUPEE', SYSDATE,SYSDATE);